### ISSUE TITLE
Publish artifact to maven central

### ISSUE THREAD

**Issue by tjake** [boundary/high-scale-lib#7]
Hi, we would like to use this library in apache cassanda but we've hit a snag when trying to build from our .pom file 

Would it be possible for you to publish this library to maven central?

see https://issues.apache.org/jira/browse/CASSANDRA-7128 for reference.

**Comment by moonpolysoft** [comment]
Put in a request with sonatype to create a repository https://issues.sonatype.org/browse/OSSRH-9817 and I'm working on the pom changes to bring it up to spec for them today.

**Comment by moonpolysoft** [comment]
http://search.maven.org/#artifactdetails%7Ccom.boundary%7Chigh-scale-lib%7C1.0.6%7Cjar

All set.

**Comment by tjake** [comment]
Thanks!
